"use client";

import { LayoutProvider } from "@/components/layoutProvider.component";
import { store } from "@/redux/store";
// import type { Metadata } from "next";
import { Provider } from "react-redux";
import { ToastContainer } from "react-toastify";

// export const metadata: Metadata = {
//     title: "Class management",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Provider store={store}>
                    <LayoutProvider>{children}</LayoutProvider>
                </Provider>
                <ToastContainer />
            </body>
        </html>
    );
}
