import { LayoutProvider } from "@/components/layoutProvider.component";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
    title: "Class management",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <LayoutProvider>{children}</LayoutProvider>
                <ToastContainer />
            </body>
        </html>
    );
}
